import { StyleSheet, Platform } from 'react-native';

export const COLORS = {
  bgDark: '#0F172A',
  cardBg: '#1E293B',
  borderDark: '#334155',
  borderLight: '#475569',
  textPrimary: '#F8FAFC',
  textSecondary: '#94A3B8',
  textMuted: '#64748B',
  accentPrimary: '#2563EB',
  accentPrimaryGlow: '#3B82F6',
  accentCyan: '#38BDF8',
  accentGreen: '#10B981',
  accentGreenBg: '#065F46',
  accentRed: '#EF4444',
  accentRedDark: '#991B1B',
  accentRedBg: '#7F1D1D',
  indigoBg: '#312E81',
  indigoBorder: '#4F46E5',
  indigoText: '#C7D2FE',
};

export const globalStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.bgDark,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 60,
  },
  scrollContentCenter: {
    padding: 24,
    paddingBottom: 60,
    flexGrow: 1,
    justifyContent: 'center',
  },
  banner: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 20,
    left: 20,
    right: 20,
    padding: 16,
    borderRadius: 12,
    zIndex: 999,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 8,
  },
  bannerError: {
    backgroundColor: COLORS.accentRedDark,
    borderLeftWidth: 5,
    borderLeftColor: COLORS.accentRed,
  },
  bannerSuccess: {
    backgroundColor: COLORS.accentGreenBg,
    borderLeftWidth: 5,
    borderLeftColor: COLORS.accentGreen,
  },
  bannerText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  subHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: COLORS.cardBg,
    marginRight: 16,
  },
  backButtonText: {
    color: COLORS.accentCyan,
    fontWeight: '600',
    fontSize: 14,
  },
  subTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  miniLogo: {
    width: 32,
    height: 32,
    borderRadius: 8,
    marginRight: 10,
  },
  formCard: {
    backgroundColor: COLORS.cardBg,
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: COLORS.borderDark,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 10,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.textSecondary,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: COLORS.bgDark,
    color: COLORS.textPrimary,
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: COLORS.borderDark,
  },
  primaryButton: {
    backgroundColor: COLORS.accentPrimary,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: COLORS.accentPrimaryGlow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    elevation: 4,
  },
  primaryButtonText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  disabledButton: {
    opacity: 0.6,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.borderDark,
    marginBottom: 24,
  },
  secondaryButtonText: {
    color: '#E2E8F0',
    fontSize: 16,
    fontWeight: '600',
  },
  tabContainer: {
    flexDirection: 'row',
    marginBottom: 24,
    backgroundColor: COLORS.bgDark,
    borderRadius: 10,
    padding: 4,
    borderWidth: 1,
    borderColor: COLORS.borderDark,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  tabButtonActive: {
    backgroundColor: COLORS.cardBg,
    borderWidth: 1,
    borderColor: '#475569',
  },
  tabButtonText: {
    color: COLORS.textMuted,
    fontWeight: '600',
    fontSize: 14,
  },
  tabButtonTextActive: {
    color: COLORS.accentCyan,
  },
});
