const nodemailer = require('nodemailer');
const { sendEmergencyPushNotification } = require('../services/pushService');
const User = require('../models/User');

// SMS Stub / future twilio setup
const sendSMS = async (to, message) => {
    console.log(`[Notification - SMS] Sending to ${to}: "${message}"`);
};

// Email sender using Nodemailer
const sendEmail = async (to, subject, text, html) => {
    console.log(`[Notification - Email] Sending to ${to} (Subject: ${subject})`);
    
    // Check if SMTP details exist in environment
    if (!process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASS) {
        console.warn('[Notification - Email] SMTP credentials not set in .env. Skipping real email dispatch, logging details instead.');
        console.log(`Email Body:\n${text}`);
        return;
    }

    try {
        const transporter = nodemailer.createTransport({
            host: process.env.SMTP_HOST,
            port: process.env.SMTP_PORT || 587,
            secure: process.env.SMTP_SECURE === 'true',
            auth: {
                user: process.env.SMTP_USER,
                pass: process.env.SMTP_PASS,
            },
        });

        await transporter.sendMail({
            from: process.env.SMTP_FROM || `"SafeCircle Security" <no-reply@safecircle.com>`,
            to,
            subject,
            text,
            html,
        });
        console.log('[Notification - Email] Email sent successfully.');
    } catch (error) {
        console.error('[Notification - Email] Error dispatching email: ', error.message);
    }
};

/**
 * Dispatch SOS alerts to all registered trusted contacts of a user
 */
const dispatchSosNotifications = async (user, contacts, alert) => {
    const alertLink = `http://localhost:${process.env.PORT || 5001}/track.html?code=`;

    for (const contact of contacts) {
        const personalLink = `${alertLink}${contact.accessCode}`;
        const messageText = `EMERGENCY ALERT: ${user.fullName} has triggered an SOS alert! Tap this link to view their real-time location and assist: ${personalLink} - SafeCircle.`;
        
        // 1. Send SMS (Twilio/Console Stub)
        await sendSMS(contact.contactPhone, messageText);

        // 2. Send Email if contact email is registered
        if (contact.contactEmail) {
            const emailSubject = `🚨 EMERGENCY: SafeCircle SOS alert for ${user.fullName}`;
            const emailHtml = `
                <div style="font-family: sans-serif; padding: 20px; color: #1e293b; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px;">
                    <h2 style="color: #dc2626; margin-top: 0;">🚨 SafeCircle Emergency SOS</h2>
                    <p>Hello <strong>${contact.contactName}</strong>,</p>
                    <p>You are receiving this message because you are listed in <strong>${user.fullName}</strong>'s safety circle.</p>
                    <p style="font-size: 16px; line-height: 1.5; background-color: #fef2f2; border-left: 4px solid #ef4444; padding: 15px; margin: 20px 0;">
                        <strong>${user.fullName}</strong> has triggered an active <strong>SOS emergency alert</strong>.
                    </p>
                    <p>Please check on them immediately. You can track their active real-time GPS coordinates and path using the secure link below:</p>
                    <p style="text-align: center; margin: 30px 0;">
                        <a href="${personalLink}" style="background-color: #dc2626; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">
                            Track Real-Time Location
                        </a>
                    </p>
                    <p style="font-size: 12px; color: #64748b; margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 20px;">
                        This is an automated alert generated by the SafeCircle Smart Security System. Your access code is <strong>${contact.accessCode}</strong>.
                    </p>
                </div>
            `;
            await sendEmail(contact.contactEmail, emailSubject, messageText, emailHtml);
        }
    }

    // 3. Dispatch FCM Push Notifications to registered contact devices
    try {
        const contactEmails = contacts.map(c => c.contactEmail).filter(Boolean);
        if (contactEmails.length > 0) {
            const contactUsers = await User.findAll({ where: { email: contactEmails } });
            const fcmTokens = contactUsers.map(u => u.fcmToken).filter(Boolean);
            if (fcmTokens.length > 0) {
                await sendEmergencyPushNotification(fcmTokens, {
                    ownerName: user.fullName,
                    message: `${user.fullName} triggered an active SOS alert! Tap to open live tracker.`,
                    alertId: alert.id,
                    deviceId: alert.deviceId,
                    latitude: alert.latitude,
                    longitude: alert.longitude,
                    alertType: alert.alertType,
                });
            }
        }
    } catch (pushErr) {
        console.error('[Notification - FCM] Error collecting contact FCM tokens:', pushErr.message);
    }
};

module.exports = {
    dispatchSosNotifications,
    sendSMS,
    sendEmail
};
